### ISSUE TITLE
Windows compatibility

### ISSUE THREAD

**Issue by dielburg** [yell0w4x/elo-touch-pi#1]
Hi.

I was trying to use this USB Gadget on Windows host. Unfortunately, when i'm connecting Raspberry PI to Windows it appears as "USB Input Device". In USB Descriptor Dumper i saw that Microsoft OS Descriptor is missing. Is it and option to add this thing to configfs script?

**Comment by yell0w4x** [comment]
I suppose the "USB Input Device" is quite ok for Windows as it is the standard HID device. I have no windows machine to try it for now. When I tried it was working quite well on win7.

Did you try using the API to make mouse pointer move? 
Did you try using the example? Does it work as expected?
On how to have deal with `configfs` please see this [manual](https://wiki.tizen.org/USB/Linux_USB_Layers/Configfs_Composite_Gadget)
